version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn todoApp.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./volumes/nginx/certs:/etc/ssl/certs

volumes:
  static_volume: